language: common-lisp

branches:
  only:
    - master
    - develop
    - /^ci-.*$/

env:
  global:
    - PATH=~/.roswell/bin:$PATH
  matrix:
    - LISP=sbcl-bin
    - LISP=ccl-bin
    - LISP=allegro
    - LISP=abcl
    - LISP=clisp
    - LISP=ecl
    - LISP=cmucl

matrix:
  allow_failures:
    - env: LISP=cmucl

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh
  - git clone --depth=1 https://gitlab.common-lisp.net/asdf/asdf.git ~/lisp/asdf

script:
  - ros -s fiveam -e '(ql:quickload :wild-package-inferred-system/test)
                      (or (fiveam:run! :wild-package-inferred-system-suite)
                          (uiop:quit 1))'

sudo: required
